name: La Fabrica Flyer AI

on:
  workflow_dispatch:

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - name: Probar GitHub Actions
        run: echo "GitHub Actions funciona correctamente"
      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: LaFabricaFlyerAI-debug
          path: LaFabricaFlyerAI/app/build/outputs/apk/debug/app-debug.apk
