name: La Fabrica Flyer AI

on:
  workflow_dispatch:

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - name: Probar GitHub Actions
        run: echo "GitHub Actions funciona correctamente"
